# Generated by Django 4.1 on 2022-08-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='uploader',
            field=models.CharField(default='', max_length=100),
        ),
    ]
