# Generated by Django 4.0.6 on 2023-04-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_file_upload_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_upload',
            name='id',
        ),
        migrations.AddField(
            model_name='file_upload',
            name='title_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
