# Generated by Django 4.0.6 on 2023-04-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_file_upload_id_file_upload_title_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='title_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
